[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["cd backend && python3.11 -m pip install --upgrade pip", "cd backend && python3.11 -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python3.11 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT"
